

export class Constants {
    public static  projects = [


        {
            "accession": "PRJEB40665",
            "title": "DTOL",
            "name":"Darwin Tree of Life Data Portal",
            "url": "https://www.darwintreeoflife.org/",
            "image":"assets/projects-logo-images/dtol-logo.png",
            "data_portal_url": "https://portal.darwintreeoflife.org/data"
        },
        {
            "accession": "PRJEB43743",
            "title": "ASG",
            "name":"The Aquatic Symbiosis Project",
            "description": "The Aquatic Symbiosis Genomics (ASG) project " +
                "(https://www.sanger.ac.uk/collaboration/aquatic-symbiosis-genomics-project/) uses high quality " +
                "references of symbiotic species to probe and understand the close association between eukaryotic " +
                "macrosymbionts and their microsymbionts in freshwater and marine ecosystems. Using genome assemblies " +
                "of both the eukaryotic \"hosts\" and their eukaryotic and prokaryotic microsymbionts, the project " +
                "is exploring the origins, ongoing evolution and future environmental resilience of symbionts such as " +
                "photosymbiotic corals, protists and molluscs, nutritional symbioses between deep sea vent animals and " +
                "sulphur bacteria and within lichens, and defensive symbioses between photoluminescent microorganisms and their animal partners. The project is a collaboration between the Tree of Life programme at the Wellcome Sanger Institute, the European Bioinformatics Institute and a ten international Hubs who coordinate with partners across the biological sciences (led by researchers at Dalhousie University, University of Rhode Island, University of California, GEOMAR Helmholtz Centre for Ocean Research, University of British Columbia, Nova Southeastern University, Queen Mary University of London, Senckenberg Research Institute, University of Vienna, University of Oregon, University of Derby, The Sainsbury Laboratory, and Portland State University). The Aquatic Symbiosis Genomics project is funded by the Gordon and Betty Moore Foundation and the Wellcome Sanger institute.",
            "url": "https://www.aquaticsymbiosisgenomics.org/",
            "image":"assets/projects-logo-images/asg-logo.png",
            "data_portal_url": "https://portal.aquaticsymbiosisgenomics.org/data"
        },
        {
            "accession": "PRJEB43510",
            "title": "ERGA",
            "name": "European Reference Genome Atlas",
            "description": "The European Reference Genome Atlas (ERGA) is a pan-European consortium with the goal of  generate high-quality annotated reference genomes for all eukaryotic species across the continent (https://www.erga-biodiversity.eu/). ERGA, as the European node of the Earth Biogenome Project (EBP) ensures, whenever possible, that genomes produced meet the EBP quality standards and assists researchers in achieving them. The data generated by the project are publicly available and adhere to the FAIR and CARE principles.",
            "url": "https://www.erga-biodiversity.eu/",
            "image":"assets/projects-logo-images/erga_logo.png",
            "data_portal_url": "https://portal.erga-biodiversity.eu/data_portal"
        },
        {
            "accession": "PRJNA163993",
            "title": "i5k initiative",
            "name": "i5k initiative",
            "description": "The i5k initiative plans to sequence the genomes of 5,000 insect and related arthropod species. This project will be transformative because it aims to sequence the genomes of all insect species known to be important to worldwide agriculture, food safety, medicine, and energy production; all those used as models in biology; the most abundant in world ecosystems; and representatives in every branch of insect phylogeny so as to achieve a deep understanding of arthropod evolution and phylogeny.",
            "url": "http://i5k.github.io/",
            "image": "assets/projects-logo-images/I5klogo4.jpg",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA489243",
            "title": "Vertebrate Genomes Project",
            "name": "Vertebrate Genomes Project",
            "description": "Reference genomes for all > 70,000 vertebrate species. The goal of the Vertebrate Genomes Project (VGP) is to generate or collect at least one high-quality, error-free, near gapless, chromosome-level, haplotype phased, and annotated reference genome assembly of all extant vertebrate species, and to utilize those genomes to address fundamental questions in biology, disease, and conservation. This umbrella BioProject ID collects all such assemblies that reach these metrics, generated by the VGP, collaborators, and others that wish to be grouped under VGP reference genomes, and that are publicly available to the community. The aspired metric minimum to be included in this list as of February 2017 are assemblies that have a contig N50 > 1Mb, scaffold N50 > 10Mb, 90% of the assembly assigned to scaffolds that represent chromosomes, base call accuracy of QV40 or greater, and haplotype phased as much as possible.",
            "url": "https://vertebrategenomesproject.org/",
            "image":"assets/projects-logo-images/VGP_Tag_RGB_newLogo_72dpi_Dots_EDIT.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA489245",
            "title": "Bat1K Project",
            "name": "Bat1K Project",
            "description": "All 1,000 bat species",
            "url": "https://bat1k.com/",
            "image":"assets/projects-logo-images/Bat1K.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA512907",
            "title": "DNA Zoo",
            "name": "DNA Zoo",
            "description": "The DNA Zoo is a consortium focused on facilitating conservation efforts through the rapid generation and release of high-quality genomics resources.",
            "url": "https://www.dnazoo.org/",
            "image":"assets/projects-logo-images/DNA-zoo.jpg"
        },
        {
            "accession": "PRJNA634441",
            "title": "Monomorium pharaonis Genome sequencing and assembly",
            "name": "Monomorium pharaonis Genome sequencing and assembly",
            "description": "The chromosome-level genome assembly of Monomorium pharaonis",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA634441",
            "url": "",
            "image": "",
            "data_portal_url": ""
        },
        {
            "accession": "PRJEB51690",
            "title": "Anopheles Reference Genomes Project (Data and assemblies)",
            "name": "Anopheles Reference Genomes Project (Data and assemblies)",
            "description": "The Anopheles Reference Genomes project builds highly complete and contiguous long-read assemblies for Anopheles species to remedy fundamental gaps in vector control, and identify a scalable blueprint for future assembly efforts. These data (including raw data and assemblies) are released for reuse for any purpose upon deposition in ENA, and we encourage reuse. Our intention is to rapidly publish all submitted assemblies as Wellcome Open Research Genome notes, which can be cited.",
            "url": "https://www.sanger.ac.uk/collaboration/anopheles-reference-genomes-project/",
            "image": "assets/projects-logo-images/Anopheles-Reference-Genomes-Project-Logo-600.jpg"
        },
        {
            "accession": "PRJNA649812",
            "title": "The Global Invertebrate Genomics Alliance (GIGA) genomes and transcriptomes",
            "name": "The Global Invertebrate Genomics Alliance (GIGA) genomes and transcriptomes",
            "description": "GIGA is a collaborative network of diverse scientists to tackle major challenges (e.g., species selection, sample collection and storage, sequence assembly, annotation, analytical tools) associated with genome/transcriptome sequencing across a large taxonomic spectrum. It aims to promote standards that will facilitate comparative approaches to invertebrate genomics and collaborations across the international scientific community.",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA649812",
            "url": "",
            "image":"assets/projects-logo-images/GIGA.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA813333",
            "title": "Canadian BioGenome Project (CBP)",
            "name": "Canadian BioGenome Project (CBP)",
            "description": "Canada possesses significant biodiversity having approximately 80,000 plant and animal species in environments ranging from desert to the arctic. The goal of the Canadian BioGenome Project (CBP) is to generate or collect a high-quality, chromosome-level, annotated reference genome assembly of Canadian eukaryotic species, and to utilize those genomes to address fundamental questions in biology, disease, and conservation. This umbrella BioProject represents the Canadian participation in the Earth BioGenome Project (EBP) (PRJNA533106). The CBP is Genome Canada's flagship Biodiversity project with three regional nodes in Toronto, ON (The Centre for Applied Genomics at The Hospital for Sick Children: https://www.tcag.ca/), Montreal, QC (McGill Genome Centre at McGill University: https://www.mcgillgenomecentre.ca/) and Vancouver, BC (Canada's Michael Smith Genome Sciences Centre (GSC) at BC Cancer: https://www.bcgsc.ca).",
            "url": "http://earthbiogenome.ca/",
            "image":"assets/projects-logo-images/cbp.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJDB6260",
            "title": "Elasmobranch shark genome evolution",
            "name": "Elasmobranch shark genome evolution",
            "description": "Modern cartilaginous fishes are divided into elasmobranchs (sharks, rays, and skates) and chimaeras, and the lack of established whole-genome sequence information for elasmobranchs has prevented our understanding of early vertebrate evolution and their unique phenotypic traits. Here we report whole genome sequencing and related molecular analysis of two elasmobranch shark species. Their genomes, whose sizes surpass that of ours, harbor sparse distribution of conserved genic and regulatory elements and exhibit reduced molecular evolutionary rates. Our investigation uncovered altered sensory gene repertory possibly associated with adaptation to unique underwater niche and relict members of the Hox C cluster previously hypothesized to be absent in elasmobranchs. We also showed the antiquity of gene repertory governing mammalian homeostasis and reproduction, including Leptin, by identifying their shark homologs. Our study provides the foundation of comprehensive exploration of morphology, physiology, and behavior of elasmobranch sharks at the molecular level, especially those with sustainable supply of animal samples.",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJDB6260",
            "url": "",
            "image":"",
            "data_portal_url": ""
        },


        {
            "accession": "PRJNA312960",
            "title": "200 Mammals",
            "name": "200 Mammals",
            "description": "Sequencing the genome of 200 mammals",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA312960",
            "url": "",
            "image":"",
            "data_portal_url": ""
        },

        {
            "accession": "PRJNA682446",
            "title": "Genome sequencing data and assemblies generated by the Lewin Lab @ UC Davis Genome Center",
            "name": "Genome sequencing data and assemblies generated by the Lewin Lab @ UC Davis Genome Center",
            "description": "Genome sequencing data and assemblies generated by the Lewin Lab @ UC Davis Genome Center.",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA682446",
            "url":"",
            "image":"",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA293101",
            "title": "Orestias ascotanensis Genome sequencing and assembly",
            "name": "Orestias ascotanensis Genome sequencing and assembly",
            "description": "Orestias ascotanensis is a fish specie that inhabit the tributaries of the Salar de Ascotan, in northern Chile. This and other species of the genus, which also inhabit salars and lakes of andean altiplane, are the result of a rapid speciation process caused by a geographic isolation (allopatric speciation).</p><p>Describing the genome of O. ascotanensis is a first approach for understanding its speciation process, and how this fish has been genetically adapted to extreme enviromental conditions.",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA293101",
            "image":"",
            "url":"",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA720569",
            "title": "The California Conservation Genomics Project (CCGP)",
            "name": "The California Conservation Genomics Project (CCGP)",
            "description": "The goal of the CCGP is to generate high quality reference genomes coupled with whole genome resequencing of hundreds of species across the range of the state of California. These data will be used to generate guidance on habitat acquisition and restoration in order to help protect the habitats and populations of threatened, endangered and exploited species.",
            "url": "https://www.ccgproject.org/",
            "image":"assets/projects-logo-images/California+Conservation+Genomics+Project+logo.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA734913",
            "title": "Amphibalanus amphitrite (Genome Sequencing and assembly)",
            "name": "Amphibalanus amphitrite (Genome Sequencing and assembly)",
            "description": "The objective of this project is to sequence, assemble, and accurately annotate the genome Acorn Barnacle, Amphibalanus amphitrite.",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA734913",
            "url": "",
            "image":"",
            "data_portal_url": ""
        },
        {
            "accession": "PRJEB33226",
            "title": "25 Genomes Project (Genome Data and Assemblies)",
            "name": "25 Genomes Project (Genome Data and Assemblies)",
            "description": "To celebrate the 25th Anniversary of the Wellcome Trust Sanger Institute, we sequenced and assembled the genomes of 25 species as the Sanger Institute’s pathfinder contribution towards the effort to sequence all life on earth.",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJEB33226",
            "url": "https://www.sanger.ac.uk/collaboration/25-genomes-for-25-years/",
            "image":"assets/projects-logo-images/25genomes600-3.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA712951",
            "title": "ENDEMIXIT",
            "name": "ENDEMIXIT",
            "description": "Genome assembly and population genomics of Italian endemics",
            "url": "https://endemixit.com/",
            "image":"assets/projects-logo-images/maxresdefault.jpg",
            "data_portal_url": ""
        },
         {   //No Public data available
            "accession": "PRJNA844590",
            "title": "Illinois EBP Pilot",
            "description": "During this pilot phase, agriculturally relevant insects for which little or no genomic data are available will serve as the focal taxa with which to demonstrate project scalability, communicate scientific discovery, and inspire potential economic and societal benefits.",
            "url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA844590",
            "image":"../assets/projects-logo-images/Illinois-EBP-Pilot.jpeg"
        },
        {
            "accession": "PRJEB49670",
            "title": "Catalan Initiative for the Earth BioGenome Project (CBP)",
            "name": "Catalan Initiative for the Earth BioGenome Project (CBP)",
            "description": "Repository for data generated from the Catalan Initiative for the Earth Biogenome Project (CBP), which aims to generate a detailed catalogue of the genomes of eukaryotic species in the Catalan Countries.",
            "url": "https://www.biogenoma.cat/",
            "image":"assets/projects-logo-images/Catalan Initiative for the Earth BioGenome Project.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA545868",
            "title": "Bird 10000 Genomes (B10K) Project (Family phase)",
            "name": "Bird 10000 Genomes (B10K) Project (Family phase)",
            "description": "The Bird 10,000 Genomes (B10K) Project is an initiative to generate representative draft genome sequences from all extant bird species. The B10K project will allow the completion of a genomic level tree of life of the entire living avian class, decode the link between genetic variation and phenotypic variation, uncover the correlation of genetic evolutionary and biogeographical and biodiversity patterns across a wide-range of species, evaluate the impact of various ecological factors and human influence on species evolution, and unveil the demographic history of an entire class of organisms. Given all these goals, the B10K project is carried out at hierarchical levels of avian classification. This Family Phase Project aims to achieve the above goals using recently generated reference genomes from 363 species representing most of the 236 avian families. This project will have significant scientific and public impact that will change our understanding of avian biology and evolution, which in turn will affect our understanding of other organisms and open doors to new areas of research.",
            "url": "https://b10k.genomics.cn/",
            "image":"assets/projects-logo-images/b10klogo.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA555319",
            "title": "USDA Agricultural Research Service’s Ag100Pest Initiative",
            "name": "USDA Agricultural Research Service’s Ag100Pest Initiative",
            "description": "The USDA Agricultural Research Service’s Ag100Pest Initiative will produce annotated, high quality genome assemblies for 100 US agricultural pest arthropods. The Ag100Pest Initiative is a component of both the i5k Initiative and Earth BioGenome Project. Species are being chosen across arthropod pests of US field crops, livestock, bees, trees, and stored products as well as foreign pest species considered potential invasive threats to US agriculture.",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA555319",
            "url": "",
            "image": "",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA706690",
            "title": "CanSeq150 Project (Genome Data and Assemblies)",
            "name": "CanSeq150 Project (Genome Data and Assemblies)",
            "description": "The CanSeq150 Project (http://www.cgen.ca/canseq150) aims to generate high-quality genomic data and genome assemblies for the 150 species of eukaryotic organisms found in Canada. The CanSeq150 project will provide 150 publicly available new reference genomes to support sequence-based genomics research, especially in biodiversity, conservation and technology development. The CanSeq150 project is CGEn’s flagship Biodiversity project with three regional nodes in Toronto, ON, Canada (Hospital for Sick Children: https://www.sickkids.ca), Montreal, Quebec, Canada (McGill University: https://www.mcgill.ca) and Vancouver, BC, Canada (The University of British Columbia (UBC): https://www.ubc.ca, Canada's Michael Smith Genome Sciences Centre (GSC) at BC Cancer: https://www.bcgsc.ca).​ A list of all funded projects is at http://www.cgen.ca/canseq150-project-list and the partners' list can be found at http://www.cgen.ca/canseq150-partners.",
            "url": "http://www.cgen.ca/canseq150",
            "image": "assets/projects-logo-images/CGen.png",
            "data_portal_url": ""
        },

        {
            "accession": "PRJNA706923",
            "title": "LOEWE Centre for Translational Biodiversity Genomics (LOEWE-TBG)",
            "name": "LOEWE Centre for Translational Biodiversity Genomics (LOEWE-TBG)",
            "description": "The LOEWE Centre for Translational Biodiversity Genomics (LOEWE TBG) aims to combine fundamental research on the genomes of a broad diversity of organisms with the development of applicable services and products. Accordingly, the central focus of LOEWE-TBG is to make genomic diversity accessible and usable as the baseline level of biodiversity for basic and applied research.",
            "url": "https://tbg.senckenberg.de/",
            "image":"assets/projects-logo-images/LOEWE-TBG.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA707598",
            "title": "Squalomix (Genome sequencing and assembly of chondrichthyans)",
            "name": "Squalomix (Genome sequencing and assembly of chondrichthyans)",
            "description": "The project Squalomix aims at unveiling the unique evolutionary trajectory of chondrichthyans (sharks, rays, and chimaeras) and is sustained by tight collaborations involving academic sequencing core facilities, marine stations, and public aquariums. By means of multimodal omics and molecular evolutionary approaches, it tackles biological questions in various fields including developmental biology and comparative physiology.",
            "ena-url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA707598",
            "url": "https://github.com/Squalomix/info",
            "image":"assets/projects-logo-images/Squalomix-logo5 (1).jpeg",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA811786",
            "title": "African BioGenome Project (AfricaBP)",
            "name": "African BioGenome Project (AfricaBP)",
            "description": "The AfricaBP initiative plans to sequence the genomes of 105,000 African endemic species. AfricaBP is a coordinated pan-African effort to build capacity to generate, analyze and deploy genomics data for the improvement and sustainable use of biodiversity and agriculture across Africa. The project aims to foster scientific collaborations and partnerships provide the platform for innovations and policy change across Africa through biodiversity genomics.",
            "url": "https://africanbiogenome.org/",
            "image":"assets/projects-logo-images/AfricaBP.jpg",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA785018",
            "title": "Genome sequencing and assembly of primate species Genome sequencing and assembly",
            "name": "Genome sequencing and assembly of primate species Genome sequencing and assembly",
            "description": "The AfricaBP initiative plans to sequence the genomes of 105,000 African endemic species. AfricaBP is a coordinated pan-African effort to build capacity to generate, analyze and deploy genomics data for the improvement and sustainable use of biodiversity and agriculture across Africa. The project aims to foster scientific collaborations and partnerships provide the platform for innovations and policy change across Africa through biodiversity genomics.",
            "url": "",
            "image":"",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA911016",
            "title": "Cephalopachus bancanus breed (not provided Genome sequencing and assembly)",
            "name": "Cephalopachus bancanus breed (not provided Genome sequencing and assembly)",
            "description": "Phylogenomic analyses provide insights into primate genomic and phenotypic evolution.",
            "url": "",
            "image":"",
            "data_portal_url": ""
        },
        {
            "accession": "PRJEB65317",
            "title": "Earth BioGenome Project Norway (EBP-Nor)",
            "name": "Earth BioGenome Project Norway (EBP-Nor)",
            "description": "Repository for data generated from EBP-Nor, the Norwegian initiative for the Earth Biogenome Project, which aims to generate a detailed catalogue of the genomes of eukaryotic species in Norway.",
            "url": "https://www.ebpnor.org/english/",
            "image":"assets/projects-logo-images/ebp_nor-orig.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJNA1120070",
            "title": "Lepus timidus genome sequencing",
            "name": "Lepus timidus genome sequencing",
            "description": "Repository for data generated from EBP-Nor, the Norwegian initiative for the Earth Biogenome Project, which aims to generate a detailed catalogue of the genomes of eukaryotic species in Norway.",
            "url": "https://www.ebpnor.org/english/",
            "image":"assets/projects-logo-images/ebp_nor-orig.png",
            "data_portal_url": ""
        },
        {
            "accession": "PRJEB65317",
            "title": "Project Psyche - Lepidopteran Genomes for Europe",
            "name": "Project Psyche - Lepidopteran Genomes for Europe",
            "description": "Project Psyche - Lepidopteran Genomes for Europe",
            "url": "https://www.projectpsyche.org/",
            "image":"assets/projects-logo-images/psyche_logo.png",
            "data_portal_url": ""
        },
         { // No data available
            "accession": "PRJNA707235",
            "title": "University of California Consortium for the Earth BioGenome Project (Cal-EBP)",
            "description": "Read data and genome assemblies produced by the University of California Consortium for the Earth BioGenome Project (Cal-EBP)",
            "url": "https://www.ebi.ac.uk/ena/browser/view/PRJNA707235"
        }
    ]
}
